### ISSUE TITLE
keyboard accessibility issues

### ISSUE THREAD

**Issue by patudom** [cosmicds/tempo-lite#37]
- [x] Radio buttons & info buttons do not activate when user presses "enter" (this is the most critical one we need to fix asap)
- [x] The credits link is skipped when tabbing around page
- [x] Some objects need a more obvious "focus" styling when the user has tabbed to that object.

**Comment by Carifio24** [comment]
I'm also noticing that when tabbing around, I can't tab to other radio buttons in the same group as the selected radio button. @patudom @johnarban do either of you notice this?

**Comment by patudom** [comment]
Oh, good catch, @Carifio24. I didn't notice that because I was tabbing around with the top "Select a Date" active.

**Comment by Carifio24** [comment]
@patudom I deleted my comment because W3C recommends [using arrow keys](https://accessibleweb.com/question-answer/how-should-keyboard-navigation-work-in-a-group-of-radio-buttons/) to navigate within a radio block, which the Vuetify radio buttons do.

**Comment by patudom** [comment]
Closing via #67
